import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

interface QuestionData {
  kind: string;
  question: string;
  options: string[];
  answer: string;
  explanation: string;
}
interface PassageData {
  slug: string;
  title: string;
  titleVi: string;
  level: string;
  category: string;
  passage: string;
  questions: QuestionData[];
}

const examSlug = "ielts-academic-test-10";

const P1_HEADINGS = [
  "i. The danger of delegating consequential judgements to opaque systems",
  "ii. Proposals for regulatory structures to govern automated decision-making",
  "iii. Why mathematical neutrality does not guarantee impartial outcomes",
  "iv. The expanding scope of computational judgement in modern institutions",
  "v. A case study revealing systematic disadvantage embedded in predictive tools",
  "vi. Theoretical objections to the very possibility of unbiased computation",
  "vii. The philosophical tension between efficiency gains and individual rights",
  "viii. Defensive strategies adopted by institutions to avoid scrutiny of their models",
  "ix. Evidence that corrective measures may inadvertently introduce new distortions",
  "x. The role of commercial incentives in perpetuating algorithmic opacity",
  "xi. Historical precedents for societies resisting technological determinism",
];

const P2_PARAGRAPHS = [
  "Paragraph A",
  "Paragraph B",
  "Paragraph C",
  "Paragraph D",
  "Paragraph E",
  "Paragraph F",
  "Paragraph G",
];

const P3_ENDINGS = [
  "the informal sector absorbs displaced rural workers who lack formal qualifications.",
  "the disparity between housing supply and demand intensifies as population density rises.",
  "municipal revenue collection often fails to keep pace with the demand for public services.",
  "cities in developing regions are expanding geographically faster than they are growing economically.",
  "rural-to-urban migration is driven primarily by perceived rather than actual opportunities.",
  "the environmental consequences of rapid urbanisation are disproportionately borne by the poorest residents.",
  "international development agencies have shifted their focus from rural agriculture to urban infrastructure.",
  "the correlation between city size and per-capita income does not hold uniformly across all regions.",
  "informal settlements often develop governance structures that formal planning frameworks fail to recognise.",
  "demographic projections suggest the majority of future global population growth will occur in cities.",
];

const passages: PassageData[] = [
  {
    slug: "mock-ac10-ethics-algorithmic-decision",
    title: "The Ethics of Algorithmic Decision-Making",
    titleVi: "Dao duc trong viec ra quyet dinh bang thuat toan",
    level: "C1",
    category: "mock-academic",
    passage: [
      "The Ethics of Algorithmic Decision-Making",
      "",
      "A. Over the past two decades, a quiet but profound transformation has reshaped the institutional landscape of modern societies: decisions that were once the exclusive province of human judgement — whom to hire, whom to lend to, whom to release on bail, whom to admit to university — are increasingly mediated, informed, or entirely determined by algorithmic systems. These systems, which range from relatively simple logistic regression models to enormously complex deep-learning neural networks, promise to deliver consistency, speed, and objectivity that human decision-makers, subject as they are to fatigue, cognitive bias, and emotional caprice, cannot reliably achieve. The appeal of this promise is considerable, and in many domains the deployment of algorithmic tools has yielded measurable improvements in predictive accuracy. Yet the enthusiasm with which institutions have embraced these technologies has, in numerous cases, outpaced careful consideration of the ethical implications that attend the delegation of consequential human decisions to computational processes whose internal logic may be opaque even to their creators.",
      "",
      "B. The most frequently articulated concern about algorithmic decision-making is the problem of bias — the risk that automated systems will reproduce, amplify, or even generate discriminatory patterns that disadvantage individuals on the basis of race, gender, socioeconomic status, or other protected characteristics. This risk might seem paradoxical, given that the explicit purpose of algorithmic decision-making is often to eliminate the subjective prejudices of human assessors. However, the apparent neutrality of mathematical computation conceals a fundamental dependency: algorithms learn from historical data, and if that data reflects the discriminatory practices, structural inequalities, or measurement artefacts of the society that generated it, the resulting model will encode those biases as statistical regularities — presenting them not as prejudice but as prediction. A hiring algorithm trained on a company's historical employment decisions, for instance, may learn that successful candidates disproportionately share characteristics correlated with demographic privilege, thereby perpetuating the very patterns of exclusion that the algorithm was ostensibly introduced to overcome.",
      "",
      "C. The case of the COMPAS (Correctional Offender Management Profiling for Alternative Sanctions) system in the American criminal justice system provides a particularly instructive illustration of these dynamics. COMPAS is a proprietary risk-assessment tool that assigns defendants a score predicting their likelihood of reoffending, and these scores are used by judges in several US states to inform sentencing and parole decisions. A landmark 2016 investigation by the non-profit journalism organisation ProPublica analysed COMPAS scores for over 7,000 defendants in Broward County, Florida, and found that the tool was roughly twice as likely to falsely flag Black defendants as future criminals compared to white defendants, while simultaneously being more likely to incorrectly label white defendants as low-risk. Northpointe, the company that developed COMPAS, contested the methodology and conclusions, arguing that the algorithm satisfied a different but equally valid statistical fairness criterion — namely, that among defendants who received a given score, the actual reoffending rate was approximately equal across racial groups. This dispute revealed a deeper and more troubling insight: mathematicians have formally demonstrated that certain widely accepted definitions of algorithmic fairness are mutually incompatible, meaning that no algorithm can simultaneously satisfy all of them when the base rates of the outcome being predicted differ across demographic groups.",
      "",
      "D. The impossibility of achieving a universally fair algorithm through purely technical means forces a confrontation with questions that are fundamentally philosophical rather than computational. When an algorithm must choose between equalising false positive rates across groups and equalising predictive accuracy within groups, it is making an implicit value judgement about which type of error is more acceptable and whose interests should be prioritised — a judgement that has historically been considered the proper domain of democratic deliberation, not automated optimisation. The efficiency gains that algorithmic systems deliver are genuine and substantial, but they exist in tension with principles of procedural justice that require affected individuals to understand the basis on which decisions about them are made, to contest those decisions through meaningful processes of appeal, and to be treated as autonomous agents rather than as data points in a statistical distribution. This tension does not admit of a straightforward resolution, and those who suggest that better data or more sophisticated models will eventually dissolve it fundamentally misapprehend its nature.",
      "",
      "E. Compounding these conceptual difficulties is the practical problem of algorithmic opacity. Many of the most powerful predictive models in current use — particularly those employing deep learning — operate as \"black boxes\" whose decision logic cannot be meaningfully explained in human-interpretable terms. A neural network with millions of parameters may identify subtle, non-linear interactions among hundreds of input variables to generate a prediction, but neither the system's developers nor its end-users can articulate precisely why a particular individual received a particular score. This opacity creates a fundamental asymmetry of power between the institution deploying the algorithm and the individual subject to its judgement: the former possesses a tool of enormous consequential authority, while the latter is denied the information necessary to understand, much less challenge, the basis on which a life-altering decision has been made. In many jurisdictions, this asymmetry is further reinforced by trade-secret protections that shield proprietary algorithms from public scrutiny.",
      "",
      "F. Several jurisdictions and regulatory bodies have begun to develop frameworks intended to address these concerns, though progress remains uneven and contested. The European Union's General Data Protection Regulation (GDPR), implemented in 2018, includes provisions that are widely interpreted as establishing a \"right to explanation\" for individuals subject to automated decision-making, though legal scholars disagree about the scope and enforceability of this right. In the United States, where no comprehensive federal legislation governs algorithmic decision-making, regulation has proceeded primarily at the municipal level — New York City's Local Law 144, enacted in 2021, requires employers using automated employment decision tools to conduct annual bias audits, though critics have noted that the law permits employers to select their own auditors and does not mandate the disclosure of audit results to affected candidates. The challenge of regulating algorithmic systems is complicated by the pace of technological change, which routinely outstrips the capacity of legislative and regulatory processes to respond.",
      "",
      "G. Perhaps most troublingly, emerging research suggests that technical interventions designed to mitigate algorithmic bias may, under certain conditions, produce paradoxical results. \"Fairness-aware\" machine learning algorithms, which incorporate explicit constraints intended to equalise outcomes across demographic groups, can in some configurations reduce overall predictive accuracy to a degree that harms the very populations they are designed to protect — for example, by reducing the precision of a medical diagnostic tool in a manner that increases missed diagnoses among minority patients. Similarly, the removal of sensitive demographic variables from an algorithm's input set — an approach sometimes termed \"fairness through unawareness\" — has been shown to be largely ineffective, as algorithms can reconstruct proxies for the removed variables from correlated features such as postal code, purchasing patterns, or even web-browsing behaviour. These findings underscore the inadequacy of purely technical solutions to what is, at its core, a problem of political philosophy: determining how the benefits and burdens of predictive technologies should be distributed across a diverse and unequally situated population.",
    ].join("\n"),
    questions: [
      { kind: "matching-headings", question: "Which heading best fits Paragraph A?", options: P1_HEADINGS, answer: "D", explanation: "Paragraph A describes how decisions once made by humans are now increasingly handled by algorithmic systems across hiring, lending, bail, and university admissions. Heading iv ('The expanding scope of computational judgement in modern institutions') captures this. Heading i ('delegating consequential judgements') is a distractor — the paragraph discusses the breadth of adoption, not specifically the danger." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph B?", options: P1_HEADINGS, answer: "C", explanation: "Paragraph B explains how algorithms trained on historical data embed existing biases, arguing that 'the apparent neutrality of mathematical computation conceals a fundamental dependency.' Heading iii ('Why mathematical neutrality does not guarantee impartial outcomes') fits precisely. Heading vi ('theoretical objections to the very possibility of unbiased computation') is a distractor — paragraph B discusses practical data bias, not theoretical impossibility." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph C?", options: P1_HEADINGS, answer: "E", explanation: "Paragraph C presents the COMPAS case study showing that the tool was twice as likely to falsely flag Black defendants as future criminals. Heading v ('A case study revealing systematic disadvantage embedded in predictive tools') matches. Heading i is a distractor." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph D?", options: P1_HEADINGS, answer: "G", explanation: "Paragraph D discusses how efficiency gains from algorithms exist 'in tension with principles of procedural justice.' Heading vii ('The philosophical tension between efficiency gains and individual rights') captures this precisely. Heading vi ('theoretical objections') is a distractor — paragraph D discusses a philosophical tension, not theoretical impossibility." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph E?", options: P1_HEADINGS, answer: "A", explanation: "Paragraph E discusses 'black box' models whose decision logic cannot be explained, creating 'a fundamental asymmetry of power.' Heading i ('The danger of delegating consequential judgements to opaque systems') matches. Heading x ('commercial incentives in perpetuating opacity') is a distractor — the paragraph mentions trade secrets but focuses on the opacity problem itself." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph F?", options: P1_HEADINGS, answer: "B", explanation: "Paragraph F describes the GDPR, NYC Local Law 144, and other regulatory efforts. Heading ii ('Proposals for regulatory structures to govern automated decision-making') fits. Heading viii ('defensive strategies adopted by institutions') is a distractor." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph G?", options: P1_HEADINGS, answer: "I", explanation: "Paragraph G describes how fairness-aware algorithms and variable removal can paradoxically harm the populations they aim to protect. Heading ix ('Evidence that corrective measures may inadvertently introduce new distortions') matches precisely." },
      { kind: "tfng", question: "The COMPAS system was developed by a government agency within the US Department of Justice.", options: ["True", "False", "Not Given"], answer: "B", explanation: "FALSE — The passage states COMPAS was developed by 'Northpointe, the company that developed COMPAS,' indicating it is a proprietary product of a private company, not a government agency." },
      { kind: "tfng", question: "ProPublica's investigation found that COMPAS was equally likely to produce false positives for Black and white defendants.", options: ["True", "False", "Not Given"], answer: "B", explanation: "FALSE — The passage explicitly states the tool 'was roughly twice as likely to falsely flag Black defendants as future criminals compared to white defendants.' The rates were unequal." },
      { kind: "tfng", question: "Mathematicians have proven that it is theoretically possible to design an algorithm that satisfies all widely accepted fairness criteria simultaneously.", options: ["True", "False", "Not Given"], answer: "B", explanation: "FALSE — The passage states the opposite: 'mathematicians have formally demonstrated that certain widely accepted definitions of algorithmic fairness are mutually incompatible.'" },
      { kind: "tfng", question: "The GDPR's provisions on automated decision-making have been uniformly interpreted by legal experts as creating an enforceable right to explanation.", options: ["True", "False", "Not Given"], answer: "B", explanation: "FALSE — The passage states the provisions 'are widely interpreted as establishing a right to explanation, though legal scholars disagree about the scope and enforceability of this right.' The interpretation is not uniform." },
      { kind: "tfng", question: "New York City's Local Law 144 was the first algorithmic regulation legislation enacted anywhere in the world.", options: ["True", "False", "Not Given"], answer: "C", explanation: "NOT GIVEN — While the passage mentions Local Law 144 was enacted in 2021, it does not state whether it was the first such legislation globally. The GDPR (2018) is mentioned earlier in the same paragraph, addressing automated decision-making." },
      { kind: "tfng", question: "Removing sensitive demographic variables from an algorithm's inputs has been shown to effectively eliminate bias in its outputs.", options: ["True", "False", "Not Given"], answer: "B", explanation: "FALSE — Paragraph G explicitly states this approach 'has been shown to be largely ineffective, as algorithms can reconstruct proxies for the removed variables from correlated features.'" },
    ],
  },

  {
    slug: "mock-ac10-human-microbiome",
    title: "The Human Microbiome and Its Influence on Health",
    titleVi: "He vi sinh vat nguoi va anh huong den suc khoe",
    level: "C1",
    category: "mock-academic",
    passage: [
      "The Human Microbiome and Its Influence on Health",
      "",
      "A. The human body, long conceptualised in biomedical science as a discrete biological entity defined by its own genome, is more accurately understood as a composite ecosystem — a \"superorganism\" in which human cells coexist with, and are profoundly influenced by, trillions of microbial inhabitants collectively termed the \"microbiome.\" Current estimates suggest that the number of bacterial cells residing in and on the human body roughly equals the number of human cells, with the vast majority concentrated in the gastrointestinal tract, particularly the large intestine, where microbial density may reach 10^11 organisms per millilitre of luminal content. These microbial communities encompass over 1,000 identified species, and their combined genetic material — the \"metagenome\" — contains approximately 150 times as many genes as the human genome itself, vastly expanding the metabolic and immunological repertoire available to the host organism. The recognition that these microbial populations are not passive hitchhikers but active participants in human physiology has catalysed one of the most significant paradigm shifts in twenty-first-century medicine.",
      "",
      "B. The establishment of the human microbiome begins at birth and is profoundly shaped by the mode of delivery. Infants delivered vaginally acquire microbial communities resembling their mother's vaginal and intestinal flora, dominated by Lactobacillus and Prevotella species that facilitate the digestion of human breast milk oligosaccharides — complex sugars that the infant's own enzymes cannot process but that serve as preferential substrates for beneficial bacteria. In contrast, infants born by Caesarean section are initially colonised by microorganisms typical of the hospital environment and the mother's skin, including Staphylococcus and Corynebacterium species, and several large-scale epidemiological studies have associated Caesarean delivery with modestly elevated risks of asthma, allergic conditions, and obesity in later childhood — associations that, while not unequivocally establishing causation, are consistent with the hypothesis that early microbial colonisation patterns exert lasting effects on immune system development. The infant microbiome continues to evolve rapidly during the first two to three years of life, influenced by breastfeeding, dietary diversification, antibiotic exposure, and environmental factors, before stabilising into an adult-like configuration that, under normal circumstances, remains relatively consistent for decades.",
      "",
      "C. Perhaps the most extensively researched dimension of microbiome function concerns its relationship with the immune system — a relationship so intimate that some immunologists have proposed that the microbiome should be considered an organ of the immune system in its own right. The gastrointestinal microbiota plays a critical role in the maturation and calibration of both innate and adaptive immune responses. Germ-free mice — animals raised in completely sterile environments and thus lacking any microbial colonisation — exhibit severely underdeveloped gut-associated lymphoid tissue, reduced production of immunoglobulin A, and impaired regulatory T-cell function, all of which can be substantially corrected by the introduction of specific commensal bacterial species. In humans, the \"hygiene hypothesis,\" first articulated by the epidemiologist David Strachan in 1989, proposed that the rising incidence of allergic and autoimmune diseases in industrialised nations might be attributable to diminished microbial exposure during early life — a thesis that has since been refined into the \"old friends\" hypothesis, which emphasises the importance of exposure to specific co-evolved microorganisms rather than microbial diversity per se.",
      "",
      "D. The discovery of the \"gut-brain axis\" — a bidirectional communication network linking the gastrointestinal tract and the central nervous system — has opened perhaps the most surprising and rapidly expanding frontier of microbiome research. This axis operates through multiple parallel channels: the vagus nerve, which provides a direct neural pathway between the enteric nervous system and the brainstem; the endocrine system, through which gut bacteria modulate the production of hormones and neurotransmitter precursors including serotonin, dopamine, and gamma-aminobutyric acid (GABA); and the immune system, through which microbially-derived inflammatory signals influence neuroinflammatory processes implicated in conditions ranging from depression to neurodegeneration. Animal studies have demonstrated that the transplantation of faecal microbiota from anxious mouse strains into germ-free recipients can induce anxiety-like behaviours in the previously unaffected animals, and conversely, that specific probiotic strains — sometimes termed \"psychobiotics\" — can attenuate stress responses and reduce behavioural indices of depression in rodent models. Translation of these findings to human clinical populations has proceeded cautiously, with several randomised controlled trials reporting modest but statistically significant improvements in self-reported mood and anxiety symptoms following probiotic supplementation, though the mechanisms, optimal strains, and durability of these effects remain subjects of active investigation.",
      "",
      "E. The therapeutic potential of microbiome manipulation is most convincingly demonstrated by the striking success of faecal microbiota transplantation (FMT) in treating recurrent Clostridioides difficile infection, a debilitating and potentially lethal condition in which the normal gut flora is decimated — typically by broad-spectrum antibiotic therapy — and replaced by an overgrowth of toxin-producing C. difficile bacteria. Systematic reviews of clinical trials have reported cure rates exceeding 90% for FMT in recurrent C. difficile infection, compared with approximately 30% for standard antibiotic therapy with vancomycin alone. This dramatic efficacy has motivated efforts to extend FMT and related microbiome-based therapies to a broader range of conditions, including inflammatory bowel disease, metabolic syndrome, and even autism spectrum disorder, though results in these areas have been considerably more variable and less conclusive. The development of defined microbial consortia — carefully selected combinations of cultured bacterial strains intended to replicate the therapeutic effects of full faecal transplants without the associated risks and aesthetic concerns — represents a particularly active area of pharmaceutical development.",
      "",
      "F. The relationship between the microbiome and metabolic health has attracted intense research interest, driven in part by the global escalation of obesity and type 2 diabetes. Studies comparing the gut microbiota of lean and obese individuals have consistently identified compositional differences, with obese individuals typically exhibiting reduced microbial diversity and altered ratios of the two dominant bacterial phyla, Firmicutes and Bacteroidetes. Crucially, experiments in germ-free mice have demonstrated that the transplantation of gut microbiota from obese human donors induces significantly greater weight gain than transplantation from lean donors, even when caloric intake is held constant — a finding that suggests the microbiome contributes causally to metabolic phenotype, not merely as a consequence of it. The mechanisms implicated include differential efficiency in extracting energy from dietary substrates, modulation of host gene expression governing lipid metabolism and insulin sensitivity, and the production of short-chain fatty acids such as butyrate, propionate, and acetate, which serve as both energy sources and signalling molecules influencing appetite, inflammation, and intestinal barrier integrity.",
      "",
      "G. Despite the remarkable pace of discovery, the field of microbiome science faces substantial methodological and interpretive challenges that counsel caution in drawing definitive conclusions. Much of the foundational research has been conducted in animal models whose relevance to human physiology, while informative, is not straightforward — the microbiome of a laboratory mouse housed in a sterile facility differs markedly from that of a wild mouse, let alone a human being. Observational studies in humans are complicated by the profound confounding effects of diet, medication use, geography, and socioeconomic status on microbiome composition, making it exceedingly difficult to disentangle cause from correlation. Furthermore, the tools of microbiome analysis — principally 16S ribosomal RNA gene sequencing and shotgun metagenomic sequencing — provide information about which organisms are present but limited insight into what those organisms are actually doing in a given physiological context. The transition from cataloguing microbial presence to understanding microbial function represents the field's most pressing intellectual challenge, one that will require the integration of metagenomics with metabolomics, transcriptomics, and sophisticated computational modelling.",
    ].join("\n"),
    questions: [
      { kind: "matching-information", question: "a description of how therapeutic microbial preparations are being refined to avoid unprocessed biological material", options: P2_PARAGRAPHS, answer: "E", explanation: "Paragraph E discusses 'defined microbial consortia — carefully selected combinations of cultured bacterial strains intended to replicate the therapeutic effects of full faecal transplants without the associated risks and aesthetic concerns.'" },
      { kind: "matching-information", question: "evidence from animal experiments establishing that gut bacteria can directly influence body weight", options: P2_PARAGRAPHS, answer: "F", explanation: "Paragraph F describes how transplanting gut microbiota from obese human donors into germ-free mice 'induces significantly greater weight gain than transplantation from lean donors, even when caloric intake is held constant.'" },
      { kind: "matching-information", question: "an explanation of how the timing and circumstances of birth affect a newborn's microbial composition", options: P2_PARAGRAPHS, answer: "B", explanation: "Paragraph B discusses how 'the mode of delivery' shapes microbial colonisation, comparing vaginal versus Caesarean delivery." },
      { kind: "matching-information", question: "a comparison of the genetic material contributed by microbial inhabitants with that of the host", options: P2_PARAGRAPHS, answer: "A", explanation: "Paragraph A states the metagenome 'contains approximately 150 times as many genes as the human genome itself.'" },
      { kind: "matching-information", question: "research demonstrating that transferring intestinal bacteria between animals can alter emotional behaviour", options: P2_PARAGRAPHS, answer: "D", explanation: "Paragraph D describes how 'transplantation of faecal microbiota from anxious mouse strains into germ-free recipients can induce anxiety-like behaviours.'" },
      { kind: "matching-information", question: "limitations of current analytical techniques in determining the active roles of microbial populations", options: P2_PARAGRAPHS, answer: "G", explanation: "Paragraph G states current tools 'provide information about which organisms are present but limited insight into what those organisms are actually doing in a given physiological context.'" },
      { kind: "matching-information", question: "a refinement of an earlier theory to emphasise specific co-evolved organisms rather than general microbial variety", options: P2_PARAGRAPHS, answer: "C", explanation: "Paragraph C describes how the hygiene hypothesis 'has since been refined into the old friends hypothesis, which emphasises the importance of exposure to specific co-evolved microorganisms rather than microbial diversity per se.'" },
      { kind: "fill-blank", question: "The combined genetic material of all microorganisms in the human body is referred to as the '______'.", options: [], answer: "metagenome|Metagenome", explanation: "Paragraph A: 'their combined genetic material — the metagenome.'" },
      { kind: "fill-blank", question: "The 'old friends' hypothesis was a refinement of the earlier hypothesis proposed by epidemiologist ______.", options: [], answer: "David Strachan|Strachan|david strachan|strachan", explanation: "Paragraph C: 'the hygiene hypothesis, first articulated by the epidemiologist David Strachan in 1989.'" },
      { kind: "fill-blank", question: "Specific probiotic strains that may influence psychological states are sometimes called '______'.", options: [], answer: "psychobiotics|Psychobiotics", explanation: "Paragraph D: 'specific probiotic strains — sometimes termed psychobiotics.'" },
      { kind: "fill-blank", question: "FMT has achieved cure rates exceeding ______% for recurrent C. difficile infection.", options: [], answer: "90", explanation: "Paragraph E: 'cure rates exceeding 90% for FMT in recurrent C. difficile infection.'" },
      { kind: "fill-blank", question: "Obese individuals typically show altered ratios of the two dominant bacterial phyla, Firmicutes and ______.", options: [], answer: "Bacteroidetes|bacteroidetes", explanation: "Paragraph F: 'altered ratios of the two dominant bacterial phyla, Firmicutes and Bacteroidetes.'" },
      { kind: "fill-blank", question: "The principal analytical tools used in microbiome research include 16S ribosomal RNA gene sequencing and ______ sequencing.", options: [], answer: "shotgun metagenomic|Shotgun metagenomic|shotgun metagenomics|metagenomic", explanation: "Paragraph G: 'principally 16S ribosomal RNA gene sequencing and shotgun metagenomic sequencing.'" },
    ],
  },

  {
    slug: "mock-ac10-urbanisation-developing-nations",
    title: "Urbanisation in Developing Nations",
    titleVi: "Do thi hoa o cac quoc gia dang phat trien",
    level: "C1",
    category: "mock-academic",
    passage: [
      "Urbanisation in Developing Nations",
      "",
      "A. The twenty-first century has been widely characterised as the \"urban century,\" and with good reason: in 2007, for the first time in human history, the global urban population surpassed the rural population, and the United Nations projects that by 2050 approximately 68% of the world's inhabitants will reside in cities. What distinguishes contemporary urbanisation from the historical urbanisation of Europe and North America, however, is both its pace and its geographical concentration. Whereas London required 130 years to grow from one million to eight million residents, Dhaka achieved the same expansion in barely 40 years, and Lagos in approximately 50. The overwhelming majority of future urban growth — an estimated 90% — will occur in Africa and Asia, regions where institutional capacity, physical infrastructure, and financial resources are frequently insufficient to accommodate the scale and velocity of demographic transformation. These projections suggest that the character of urbanisation in developing nations will define many of the most consequential economic, environmental, and political challenges of the coming decades.",
      "",
      "B. The economic drivers of urbanisation in developing countries differ in important respects from the pattern that characterised industrialising Europe. The classical model of structural transformation, associated with the economist W. Arthur Lewis, describes urbanisation as a consequence of industrialisation: as productivity gains in agriculture release surplus labour, workers migrate to cities where expanding manufacturing sectors offer higher wages, driving a virtuous cycle of capital accumulation, technological advancement, and rising living standards. In much of contemporary sub-Saharan Africa and South Asia, however, urbanisation is occurring in the relative absence of industrialisation — a phenomenon some economists have termed \"urbanisation without growth.\" Cities are expanding not because urban economies are generating productive employment at a rate commensurate with population influx, but because rural conditions — land fragmentation, declining soil fertility, climatic instability, and the collapse of smallholder commodity prices — have become sufficiently desperate to push inhabitants toward cities despite the uncertain prospects that await them. The result is what the urbanist Mike Davis has called \"a planet of slums\": cities whose populations vastly exceed the capacity of their formal economies and physical infrastructure.",
      "",
      "C. The spatial manifestation of this process is the proliferation of informal settlements — variously termed slums, favelas, bidonvilles, or bustees — which now house an estimated one billion people worldwide, a figure projected to double by 2030. These settlements are characterised by insecure land tenure, inadequate access to clean water and sanitation, overcrowding, and structures built from impermanent materials on land that is frequently environmentally hazardous — floodplains, steep hillsides, or sites adjacent to industrial waste. Yet the characterisation of informal settlements as undifferentiated zones of deprivation obscures a more nuanced reality. Many such communities develop sophisticated internal governance mechanisms, including informal property-rights systems, community-managed water distribution, conflict-resolution protocols, and savings cooperatives, that represent rational adaptive responses to the failure of formal institutions to provide basic services. The challenge for urban policy, accordingly, is not simply to eradicate informal settlements but to recognise the social capital embedded within them and to develop upgrading strategies that build upon, rather than destroy, existing community structures.",
      "",
      "D. The fiscal dimensions of rapid urbanisation in developing countries present a particularly intractable set of challenges. Municipal governments in these contexts typically operate under severe resource constraints: their tax bases are narrow, collection mechanisms are weak, and the ratio of taxable formal-sector economic activity to total urban economic activity is often unfavourable, given the large share of employment and commerce that occurs in the informal economy. In Lagos, Nigeria, for example, the state government collects tax revenue equivalent to less than 1% of the city's gross domestic product — a figure that renders meaningful investment in infrastructure, public transport, healthcare, and education effectively impossible without substantial intergovernmental transfers or external financing. The structural mismatch between the revenues available to municipal authorities and the expenditure demands generated by rapid population growth creates a vicious cycle in which inadequate public services further discourage formal economic activity, thereby eroding the tax base still further.",
      "",
      "E. Perhaps the most counterintuitive feature of urbanisation in developing countries is the extent to which it is driven by perception rather than reality. Empirical research consistently demonstrates that prospective migrants systematically overestimate the economic opportunities available in cities and underestimate the costs — both financial and psychological — of urban life. The Nobel laureate economist John Harris and the development economist Michael Todaro formalised this insight in their influential 1970 model, which posits that migration decisions are determined not by actual urban-rural wage differentials but by expected wage differentials, calculated by multiplying the urban wage premium by the probability of obtaining formal-sector employment. Because the probability of employment may be quite low — often below 50% — the expected benefit of migration may be considerably smaller than the nominal wage gap would suggest, yet migrants nonetheless move because they overweight the prospect of a transformative improvement in circumstances relative to the certainty of continued rural poverty. This dynamic helps explain why cities continue to grow even when urban unemployment rates are high and the material conditions of the urban poor are, by some measures, no better than those of the rural populations they have left behind.",
      "",
      "F. The environmental consequences of rapid, unplanned urbanisation in developing regions constitute a crisis of growing urgency. Urban expansion in these contexts frequently occurs through the conversion of agricultural land, wetlands, and forests on the urban periphery — processes that destroy ecosystems, reduce biodiversity, and compromise the environmental services upon which the city itself depends, including flood attenuation, water filtration, and local climate regulation. Within cities, the absence of adequate waste-management infrastructure means that solid waste and untreated sewage often contaminate waterways, groundwater, and soil, with disproportionate health impacts on the populations residing in informal settlements closest to these pollution sources. Air quality in rapidly urbanising cities in South and Southeast Asia now ranks among the most hazardous in the world, driven by vehicular emissions from aging, poorly maintained fleets operating in the absence of effective emissions standards, combined with industrial pollution and the domestic burning of solid fuels for cooking. The WHO estimates that outdoor air pollution causes approximately 4.2 million premature deaths annually, the majority in low- and middle-income countries, with urban populations bearing the greatest burden.",
      "",
      "G. Addressing the challenges of urbanisation in developing nations requires an approach that transcends the conventional dichotomy between formal planning and informal self-organisation. The most promising strategies emerging from cities in the Global South combine top-down investment in trunk infrastructure — water mains, sewer networks, arterial roads, and public transport systems — with bottom-up processes of community-led planning, participatory budgeting, and incremental housing improvement. Medellin, Colombia, once notorious as one of the world's most violent cities, has been widely cited as a model for this approach: its integrated urban projects combined cable-car transit systems linking hillside informal settlements to the city centre, library-parks in previously underserved communities, and land-regularisation programmes that extended formal property titles to long-term informal residents. Similarly, programmes such as Baan Mankong in Thailand, which channels government subsidies directly to organised community networks rather than to developers or contractors, have demonstrated that community-driven upgrading can achieve superior outcomes at lower cost than conventional public housing approaches. The transferability of these models, however, depends critically on local political conditions, institutional capacity, and the willingness of national governments to devolve authority and resources to the municipal level.",
    ].join("\n"),
    questions: [
      { kind: "matching-sentence-endings", question: "The passage states that contemporary urbanisation differs from historical patterns because...", options: P3_ENDINGS, answer: "D", explanation: "Paragraph A contrasts current urbanisation with historical patterns, noting that cities in developing regions are growing at extraordinary speed without commensurate economic development. Ending D ('cities in developing regions are expanding geographically faster than they are growing economically') captures this." },
      { kind: "matching-sentence-endings", question: "According to the passage, in many developing countries, people move to cities because...", options: P3_ENDINGS, answer: "E", explanation: "Paragraph E discusses the Harris-Todaro model showing migration is driven by expected rather than actual wage differentials — people overestimate urban opportunities. Ending E ('rural-to-urban migration is driven primarily by perceived rather than actual opportunities') matches." },
      { kind: "matching-sentence-endings", question: "The passage indicates that informal settlements often possess...", options: P3_ENDINGS, answer: "I", explanation: "Paragraph C describes how 'many such communities develop sophisticated internal governance mechanisms' that formal planning fails to recognise. Ending I ('informal settlements often develop governance structures that formal planning frameworks fail to recognise') matches." },
      { kind: "matching-sentence-endings", question: "The fiscal problems faced by rapidly growing cities in developing nations arise partly because...", options: P3_ENDINGS, answer: "C", explanation: "Paragraph D describes how municipal governments have narrow tax bases and weak collection mechanisms, with Lagos collecting less than 1% of GDP in tax revenue. Ending C ('municipal revenue collection often fails to keep pace with the demand for public services') matches." },
      { kind: "matching-sentence-endings", question: "The passage suggests that the health impacts of urban environmental degradation...", options: P3_ENDINGS, answer: "F", explanation: "Paragraph F states pollution has 'disproportionate health impacts on the populations residing in informal settlements closest to these pollution sources.' Ending F ('the environmental consequences of rapid urbanisation are disproportionately borne by the poorest residents') matches." },
      { kind: "matching-sentence-endings", question: "The passage implies that in the absence of formal employment growth, cities expand because...", options: P3_ENDINGS, answer: "A", explanation: "Paragraph B describes urbanisation without industrialisation where cities grow despite the absence of productive formal jobs; Paragraph C notes informal settlements housing a billion people. Ending A ('the informal sector absorbs displaced rural workers who lack formal qualifications') captures this dynamic." },
      { kind: "matching-sentence-endings", question: "United Nations projections indicate that...", options: P3_ENDINGS, answer: "J", explanation: "Paragraph A states that by 2050, approximately 68% of the world's population will reside in cities, with 90% of growth in Africa and Asia. Ending J ('demographic projections suggest the majority of future global population growth will occur in cities') matches." },
      { kind: "mcq", question: "The author uses the comparison between London's growth and that of Dhaka and Lagos primarily to illustrate...", options: ["the superiority of European urban planning over Asian and African models", "the unprecedented speed at which cities in developing regions are expanding", "the inadequacy of colonial infrastructure left behind in developing nations", "the relationship between population growth and economic prosperity in megacities"], answer: "B", explanation: "The comparison (London: 130 years vs. Dhaka: 40 years, Lagos: 50 years) is used to demonstrate the exceptional pace of contemporary urbanisation, not to comment on planning quality or colonial legacies." },
      { kind: "mcq", question: "The concept of 'urbanisation without growth' as described in the passage refers to...", options: ["cities that maintain stable populations despite economic expansion", "urban areas that grow in population without corresponding industrial development", "the deliberate government policy of restricting urban economic investment", "a temporary phase of urban stagnation that precedes rapid industrialisation"], answer: "B", explanation: "Paragraph B explicitly defines this as urbanisation 'occurring in the relative absence of industrialisation' — cities growing in population without productive economic expansion." },
      { kind: "mcq", question: "According to the Harris-Todaro model discussed in the passage, migration to cities continues even when...", options: ["governments offer financial incentives to encourage rural-to-urban relocation", "the actual probability of obtaining urban employment is lower than migrants assume", "urban wages are lower than rural wages for equivalent occupations", "rural communities actively discourage residents from remaining in agricultural work"], answer: "B", explanation: "Paragraph E states migrants move because they 'overweight the prospect of a transformative improvement' even though 'the probability of employment may be quite low — often below 50%.' The model explains migration based on expected (not actual) outcomes." },
      { kind: "mcq", question: "The passage presents Medellin's urban transformation primarily as an example of...", options: ["how private-sector investment can single-handedly revitalise disadvantaged urban areas", "the successful integration of institutional investment with community-based participation", "a uniquely Latin American approach that cannot be replicated in other cultural contexts", "the effectiveness of demolishing informal settlements and replacing them with planned housing"], answer: "B", explanation: "Paragraph G describes Medellin's 'integrated urban projects' combining top-down infrastructure (cable cars, library-parks) with bottom-up processes (land regularisation for existing residents). This exemplifies the passage's argument for combining formal planning with community participation." },
      { kind: "mcq", question: "The author's overall tone toward urbanisation in developing countries can best be described as...", options: ["pessimistic, suggesting that the problems are fundamentally unsolvable", "analytical, acknowledging both the severity of challenges and the existence of promising approaches", "dismissive, arguing that urbanisation is merely a continuation of colonial exploitation", "optimistic, proposing that market forces will naturally resolve urban inequality"], answer: "B", explanation: "The passage thoroughly analyses the challenges (fiscal, environmental, social) while also highlighting promising strategies (Medellin, Baan Mankong), maintaining a balanced analytical tone throughout rather than pure pessimism or optimism." },
      { kind: "mcq", question: "The passage suggests that the Baan Mankong programme in Thailand is significant because it demonstrates that...", options: ["international development agencies are more effective than local governments at managing urban projects", "directing resources to community organisations can produce better results than conventional housing programmes", "the private construction industry is inherently exploitative of low-income urban residents", "community-led initiatives only succeed when they operate entirely without government involvement"], answer: "B", explanation: "Paragraph G states Baan Mankong 'channels government subsidies directly to organised community networks rather than to developers or contractors' and has 'demonstrated that community-driven upgrading can achieve superior outcomes at lower cost than conventional public housing approaches.'" },
      { kind: "mcq", question: "Which of the following best summarises the passage's main argument?", options: ["Urbanisation in developing nations is primarily caused by overpopulation and can only be addressed through population control measures", "The rapid urbanisation of developing countries presents complex, interrelated challenges that require integrated approaches combining formal and informal strategies", "Developing nations should resist urbanisation and invest primarily in rural development to prevent further urban growth", "The environmental costs of urbanisation in developing nations outweigh any potential economic benefits of city growth"], answer: "B", explanation: "The passage systematically examines economic, spatial, fiscal, perceptual, and environmental dimensions of urbanisation, concluding with the argument that solutions must 'transcend the conventional dichotomy between formal planning and informal self-organisation' — an integrated approach." },
    ],
  },
];

async function main() {
  const passageIds: string[] = [];

  for (const p of passages) {
    const wc = p.passage.split(/\s+/).filter(Boolean).length;
    const passage = await prisma.readingPassage.upsert({
      where: { slug: p.slug },
      update: { title: p.title, titleVi: p.titleVi, level: p.level, category: p.category, passage: p.passage, wordCount: wc, order: 960 + passages.indexOf(p) },
      create: { slug: p.slug, title: p.title, titleVi: p.titleVi, level: p.level, category: p.category, passage: p.passage, wordCount: wc, order: 960 + passages.indexOf(p) },
    });
    await prisma.readingQuestion.deleteMany({ where: { passageId: passage.id } });
    for (let q = 0; q < p.questions.length; q++) {
      const qn = p.questions[q];
      await prisma.readingQuestion.create({
        data: {
          passageId: passage.id,
          kind: qn.kind,
          question: qn.question,
          options: qn.options,
          answer: qn.answer,
          explanation: qn.explanation,
          order: q,
        },
      });
    }
    passageIds.push(passage.id);
    console.log("  OK [" + p.level + "] " + p.slug + " (" + wc + " words, " + p.questions.length + " questions)");
  }

  const exam = await prisma.readingExam.upsert({
    where: { slug: examSlug },
    update: { title: "IELTS Academic Reading — Test 10", titleVi: "IELTS Academic Reading — Đề 10", type: "academic", difficulty: "hard", timeMinutes: 60 },
    create: { slug: examSlug, title: "IELTS Academic Reading — Test 10", titleVi: "IELTS Academic Reading — Đề 10", type: "academic", difficulty: "hard", timeMinutes: 60, order: 9 },
  });
  console.log("\n  OK Exam: " + exam.slug + " (difficulty: hard)");
  await prisma.readingExamSection.deleteMany({ where: { examId: exam.id } });
  for (let i = 0; i < passageIds.length; i++) {
    await prisma.readingExamSection.create({ data: { examId: exam.id, passageId: passageIds[i], order: i } });
  }
  console.log("Done! 3 passages (" + passages.reduce((s, p) => s + p.questions.length, 0) + " questions) + exam + sections.");
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
