import "dotenv/config";
import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

interface QuestionData {
  kind: string;
  question: string;
  options: string[];
  answer: string;
  explanation: string;
}
interface PassageData {
  slug: string;
  title: string;
  titleVi: string;
  level: string;
  category: string;
  passage: string;
  questions: QuestionData[];
}

const examSlug = "ielts-academic-test-11";

/* ── shared option arrays ─────────────────────────────────── */

const P1_HEADINGS = [
  "i. The paradoxical enhancement of certain faculties under conditions of exhaustion",
  "ii. Corporate and institutional failures rooted in insufficient rest",
  "iii. Why the brain's emotional circuitry becomes disproportionately reactive",
  "iv. Distinguishing between the subjective perception and measurable reality of impairment",
  "v. The cumulative physiological toll of sustained wakefulness",
  "vi. Pharmaceutical interventions and their inherent limitations",
  "vii. A reconsideration of longstanding assumptions about the necessity of rest",
  "viii. Historical events attributable to fatigue-related judgement errors",
  "ix. The differential vulnerability of distinct cognitive operations",
  "x. Cultural attitudes that inadvertently promote chronic under-sleeping",
  "xi. How restricted sleep compromises the body's defensive mechanisms",
];

const P2_PARAGRAPHS = [
  "Paragraph A",
  "Paragraph B",
  "Paragraph C",
  "Paragraph D",
  "Paragraph E",
  "Paragraph F",
  "Paragraph G",
];

const P3_ENDINGS = [
  "the direction of individual strokes became standardised across the scribal community.",
  "a single writing system could be adapted to represent languages with fundamentally different structures.",
  "the original pictographic connection between sign and referent was progressively obscured.",
  "the invention resolved a limitation that had constrained all previous representational strategies.",
  "political unification created administrative demands that purely oral communication could not fulfil.",
  "the transition from ideographic to phonetic representation occurred independently in multiple civilisations.",
  "economic imperatives drove the simplification of complex symbolic inventories.",
  "archaeological evidence has conclusively established the precise date of the earliest script.",
  "religious institutions actively suppressed the development of vernacular writing traditions.",
  "modern digital communication has reversed the millennia-long trend toward phonetic transparency.",
];

const passages: PassageData[] = [

  // ═══════════════════════════════════════════════════════════
  // PASSAGE 1: The Neuroscience of Sleep Deprivation (C1, ~950 words, 13 questions)
  // ═══════════════════════════════════════════════════════════
  {
    slug: "mock-ac11-neuroscience-sleep-deprivation",
    title: "The Neuroscience of Sleep Deprivation",
    titleVi: "Khoa hoc than kinh ve thieu ngu",
    level: "C1",
    category: "mock-academic",
    passage: [
      "The Neuroscience of Sleep Deprivation",
      "",
      "A. For much of the twentieth century, sleep was regarded within mainstream neuroscience as a passive state — a mere cessation of wakefulness whose primary function, if it could be said to possess one at all, was the conservation of metabolic energy. This characterisation, which rendered sleep essentially epiphenomenal, began to unravel in the 1950s with the discovery of rapid eye movement (REM) phases and the realisation that the sleeping brain exhibits patterns of neural activity as complex as, and in some respects more intense than, those observed during waking cognition. Contemporary research has since established that sleep is not a luxury but a biological imperative, orchestrating processes — from synaptic consolidation and metabolic waste clearance to hormonal regulation and immunological maintenance — without which sustained physiological and cognitive functioning rapidly deteriorates. The consequences of its deprivation, once dismissed as mere drowsiness, are now understood to pervade virtually every organ system and cognitive domain.",
      "",
      "B. The cognitive deficits produced by insufficient sleep are both more varied and more insidious than popular understanding typically acknowledges. Laboratory studies employing sustained wakefulness protocols have demonstrated that after approximately seventeen hours without sleep, performance on tests of reaction time, vigilance, and working memory degrades to levels statistically equivalent to those exhibited by individuals with a blood alcohol concentration of 0.05% — the legal intoxication threshold in many jurisdictions. After twenty-four hours of wakefulness, this equivalence rises to 0.10%, a level at which operating a motor vehicle is illegal in every developed nation. Yet the degradation is not uniform across cognitive functions. Executive processes — those responsible for planning, flexible reasoning, innovation, and the inhibition of inappropriate responses — appear disproportionately vulnerable, declining measurably after even modest reductions in sleep duration, while more routinised procedural skills may be preserved until exhaustion is far more severe.",
      "",
      "C. Perhaps the most treacherous feature of sleep deprivation is the dissociation it produces between subjective and objective measures of impairment. Individuals who have experienced chronic partial sleep restriction — sleeping five or six hours per night over a period of weeks, a pattern common among professionals in medicine, finance, and technology — consistently rate their cognitive abilities as substantially intact even as standardised testing reveals progressive, cumulative deterioration. A landmark 2003 study by Hans Van Dongen and colleagues at the University of Pennsylvania demonstrated that subjects restricted to six hours of sleep per night for fourteen consecutive days exhibited cognitive deficits equivalent to those produced by two full nights of total sleep deprivation, yet reported only modest increases in subjective sleepiness. This metacognitive blind spot — the inability to accurately assess one's own degree of impairment — transforms chronic sleep debt from a merely physiological condition into an epistemic one, in which the affected individual lacks the very faculty needed to recognise the problem.",
      "",
      "D. The neurological mechanisms underlying these deficits have been substantially elucidated by functional neuroimaging studies conducted over the past two decades. Sleep deprivation produces a characteristic pattern of reduced activation in the prefrontal cortex — the brain region most closely associated with executive function, decision-making, and impulse regulation — accompanied by a paradoxical hyperactivation of the amygdala, the structure central to the processing of threat and emotional salience. Matthew Walker's research group at the University of California, Berkeley, demonstrated that sleep-deprived individuals exhibited amygdala responses to negative emotional stimuli that were approximately 60% greater in magnitude than those of well-rested controls, coupled with a significant weakening of the functional connectivity between the amygdala and the medial prefrontal cortex — the pathway that, under normal conditions, provides top-down regulatory modulation of emotional reactivity. The practical consequence is a brain in which the emotional accelerator is pressed harder while the rational brake is simultaneously disengaged.",
      "",
      "E. Beyond cognition and emotional regulation, sleep deprivation exerts profound effects on physiological systems that are frequently overlooked in discussions focused narrowly on mental performance. The immune system is particularly susceptible: a single night of restricted sleep — four hours rather than eight — has been shown to reduce natural killer cell activity by approximately 70%, a deficit with direct implications for cancer surveillance, given that natural killer cells constitute the body's primary defence against the emergence of malignant tumour cells. Chronic sleep restriction elevates circulating levels of inflammatory markers including C-reactive protein and interleukin-6, increases insulin resistance in a pattern that mirrors the metabolic profile of pre-diabetes, raises systolic blood pressure, and disrupts the regulation of appetite-controlling hormones leptin and ghrelin in ways that promote weight gain. Epidemiological data consistently associate habitual short sleep — defined as fewer than six hours per night — with significantly elevated risks of cardiovascular disease, type 2 diabetes, obesity, and all-cause mortality.",
      "",
      "F. The societal costs of widespread sleep insufficiency extend well beyond individual health outcomes. Investigations into major industrial and transportation disasters have repeatedly identified fatigue-related impairment as a contributing or proximate cause. The nuclear accidents at Three Mile Island in 1979 and Chernobyl in 1986 both involved critical errors committed by operators working extended overnight shifts. The Exxon Valdez oil spill of 1989, the Challenger space shuttle disaster of 1986, and numerous aviation incidents have been linked, at least in part, to decision-makers operating under conditions of significant sleep debt. The American Academy of Sleep Medicine has estimated that sleep deprivation costs the United States economy approximately 411 billion dollars annually in lost productivity, healthcare expenditure, and accident-related damages — a figure that exceeds the gross domestic product of most nations.",
      "",
      "G. Despite the mounting evidence of its hazards, insufficient sleep remains deeply embedded in the cultural fabric of many industrialised societies. The valorisation of long working hours, the stigmatisation of adequate rest as indicative of indolence or insufficient ambition, and the pervasive availability of artificial stimulants — particularly caffeine, which operates by blocking adenosine receptors and thereby masking, without eliminating, the homeostatic drive to sleep — collectively sustain what the neuroscientist Matthew Walker has termed a \"silent epidemic\" of chronic sleep deprivation. While pharmacological wakefulness-promoting agents such as modafinil can temporarily restore certain aspects of cognitive performance, they do not replicate the full restorative functions of natural sleep, leaving the underlying physiological debt unresolved. The emerging scientific consensus is unequivocal: no pharmacological substitute for sleep has been identified, and none is theoretically likely to be, given the multiplicity and complexity of the biological processes that sleep uniquely enables.",
    ].join("\n"),
    questions: [
      { kind: "matching-headings", question: "Which heading best fits Paragraph A?", options: P1_HEADINGS, answer: "G", explanation: "Paragraph A describes how the earlier view of sleep as merely passive energy conservation has been overturned by modern research. Heading vii ('A reconsideration of longstanding assumptions about the necessity of rest') captures this precisely. Heading i ('paradoxical enhancement') is a distractor — the paragraph mentions intense neural activity during sleep but does not discuss enhanced faculties under exhaustion." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph B?", options: P1_HEADINGS, answer: "I", explanation: "Paragraph B shows that executive processes are disproportionately vulnerable while routinised procedural skills are more preserved — different cognitive operations are differentially affected. Heading ix ('The differential vulnerability of distinct cognitive operations') matches. Heading iv is a distractor — subjective vs. objective impairment is covered in Paragraph C, not B." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph C?", options: P1_HEADINGS, answer: "D", explanation: "Paragraph C focuses on the gap between how impaired people feel (subjective) versus how impaired they actually are (objective). Heading iv ('Distinguishing between the subjective perception and measurable reality of impairment') fits precisely. Heading ii ('Corporate failures') is a distractor." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph D?", options: P1_HEADINGS, answer: "C", explanation: "Paragraph D explains the amygdala hyperactivation and prefrontal cortex underactivation that produces exaggerated emotional responses. Heading iii ('Why the brain's emotional circuitry becomes disproportionately reactive') matches. Heading ix is a distractor — while D discusses brain mechanisms, the paragraph's focus is specifically on emotional reactivity, not differential cognitive vulnerability." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph E?", options: P1_HEADINGS, answer: "K", explanation: "Paragraph E discusses how sleep deprivation reduces natural killer cell activity, elevates inflammatory markers, and disrupts metabolic regulation — all physiological defence systems. Heading xi ('How restricted sleep compromises the body's defensive mechanisms') matches. Heading v ('cumulative physiological toll') is a plausible distractor but is less precise — Paragraph E specifically focuses on immune and defensive systems." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph F?", options: P1_HEADINGS, answer: "H", explanation: "Paragraph F cites Three Mile Island, Chernobyl, the Exxon Valdez spill, and the Challenger disaster as events caused by fatigue-related errors. Heading viii ('Historical events attributable to fatigue-related judgement errors') matches directly. Heading ii ('Corporate and institutional failures') is a distractor — while the disasters involved institutions, the paragraph emphasises historical catastrophic events, not corporate culture." },
      { kind: "matching-headings", question: "Which heading best fits Paragraph G?", options: P1_HEADINGS, answer: "J", explanation: "Paragraph G discusses how valorisation of overwork, stigmatisation of rest, and availability of caffeine sustain chronic sleep deprivation in industrialised societies. Heading x ('Cultural attitudes that inadvertently promote chronic under-sleeping') captures this. Heading vi ('Pharmaceutical interventions') is a distractor — while modafinil is mentioned, it is secondary to the cultural analysis." },
      { kind: "tfng", question: "After seventeen hours of sustained wakefulness, cognitive performance declines to a level comparable to the legal alcohol limit in all countries.", options: ["True", "False", "Not Given"], answer: "B", explanation: "FALSE — The passage states performance becomes equivalent to a blood alcohol concentration of 0.05%, which it describes as 'the legal intoxication threshold in many jurisdictions' — not all countries. The word 'many' is critical." },
      { kind: "tfng", question: "In the Van Dongen study, subjects sleeping six hours per night for fourteen days showed cognitive impairment equivalent to two nights without any sleep.", options: ["True", "False", "Not Given"], answer: "A", explanation: "TRUE — The passage explicitly states: 'subjects restricted to six hours of sleep per night for fourteen consecutive days exhibited cognitive deficits equivalent to those produced by two full nights of total sleep deprivation.'" },
      { kind: "tfng", question: "Matthew Walker's research found that the amygdala response to positive emotional images was also heightened by sleep deprivation.", options: ["True", "False", "Not Given"], answer: "C", explanation: "NOT GIVEN — The passage only mentions amygdala responses to 'negative emotional stimuli.' It does not address whether responses to positive stimuli were also heightened." },
      { kind: "tfng", question: "The Challenger space shuttle disaster occurred partly because the decision-makers had not slept for more than forty-eight hours.", options: ["True", "False", "Not Given"], answer: "C", explanation: "NOT GIVEN — The passage states the Challenger disaster has been 'linked, at least in part, to decision-makers operating under conditions of significant sleep debt' but does not specify the duration of sleep deprivation involved." },
      { kind: "tfng", question: "Caffeine eliminates the body's physiological need for sleep by blocking adenosine receptors.", options: ["True", "False", "Not Given"], answer: "B", explanation: "FALSE — The passage states caffeine operates 'by blocking adenosine receptors and thereby masking, without eliminating, the homeostatic drive to sleep.' It masks the need; it does not eliminate it." },
      { kind: "tfng", question: "The economic cost of sleep deprivation to the United States exceeds the GDP of most countries.", options: ["True", "False", "Not Given"], answer: "A", explanation: "TRUE — The passage states the annual cost is 'approximately 411 billion dollars... a figure that exceeds the gross domestic product of most nations.'" },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // PASSAGE 2: Deep-Sea Mining (C1, ~950 words, 13 questions)
  // ═══════════════════════════════════════════════════════════
  {
    slug: "mock-ac11-deep-sea-mining",
    title: "Deep-Sea Mining and Its Environmental Implications",
    titleVi: "Khai thac day bien va cac tac dong moi truong",
    level: "C1",
    category: "mock-academic",
    passage: [
      "Deep-Sea Mining and Its Environmental Implications",
      "",
      "A. The accelerating global transition toward renewable energy technologies — solar photovoltaics, wind turbines, electric vehicle batteries, and grid-scale energy storage systems — has generated an irony that policymakers and environmentalists are only beginning to confront: the very technologies designed to reduce humanity's dependence on fossil fuels require vast quantities of metallic minerals whose terrestrial supplies are geographically concentrated, geopolitically contested, and, in several critical cases, approaching projected depletion within decades. Cobalt, nickel, manganese, copper, and rare earth elements constitute the essential material substrate of the green energy revolution, yet their extraction through conventional land-based mining entails its own catalogue of environmental degradation — deforestation, toxic tailings, water contamination, and habitat destruction. It is within this paradox that deep-sea mining has emerged as a proposed alternative, promising access to mineral reserves of extraordinary concentration deposited across the abyssal plains of the world's oceans.",
      "",
      "B. The mineral deposits that have attracted the most commercial and scientific attention occur in three principal formations, each located in distinct oceanic environments and presenting unique extraction challenges. Polymetallic nodules — roughly potato-sized concretions of manganese, nickel, cobalt, and copper — litter the sediment surface of abyssal plains at depths between 4,000 and 6,000 metres, with the Clarion-Clipperton Zone in the central Pacific Ocean containing the largest known concentration. These nodules form through the excruciatingly slow precipitation of dissolved metals around a nucleus, such as a shark tooth or fragment of bone, accreting at rates of approximately five to twenty millimetres per million years — a timescale that renders them, for all practical purposes, non-renewable. Seafloor massive sulphide deposits, formed at hydrothermal vents where superheated, mineral-laden water erupts from the ocean crust, contain elevated concentrations of copper, zinc, gold, and silver. Cobalt-rich ferromanganese crusts, which coat the surfaces of seamounts at depths between 800 and 2,500 metres, represent a third category rich in cobalt, tellurium, and other metals critical to high-technology manufacturing.",
      "",
      "C. The regulatory framework governing deep-sea mining in international waters falls under the jurisdiction of the International Seabed Authority (ISA), a United Nations body established by the 1982 United Nations Convention on the Law of the Sea and headquartered in Kingston, Jamaica. The Convention designates the mineral resources of the international seabed as the \"common heritage of mankind\" — a legal principle intended to ensure that the benefits of exploitation are shared equitably among all nations, including landlocked and developing states. The ISA has issued thirty-one exploration contracts to state-sponsored and private entities, permitting geological surveys and environmental baseline studies across vast tracts of the Pacific, Atlantic, and Indian Oceans. However, as of mid-2024, no commercial extraction licence had been granted, with negotiations over the Mining Code — the regulatory instrument that would establish environmental standards, royalty structures, and benefit-sharing mechanisms — remaining mired in protracted disagreement among member states.",
      "",
      "D. The environmental concerns surrounding deep-sea mining are substantial and, in significant respects, qualitatively different from those associated with terrestrial extraction. The abyssal ecosystems that would be directly disturbed by nodule collection are among the least understood biomes on Earth, characterised by extreme pressure, perpetual darkness, near-freezing temperatures, and severely limited food supply. Despite these seemingly inhospitable conditions, research expeditions have revealed surprising levels of biodiversity. Studies in the Clarion-Clipperton Zone have identified over 5,000 species, of which an estimated 70% to 90% are new to science. Many of these organisms — including xenophyophores, polychaete worms, and diverse microbial communities — have adapted specifically to life on or around polymetallic nodules, which provide the only hard substrate on an otherwise featureless sedimentary plain. The removal of nodules would therefore eliminate not merely a mineral resource but the primary habitat upon which an entire assemblage of specialist organisms depends.",
      "",
      "E. The physical disturbance caused by mining operations extends well beyond the immediate extraction site through the generation of sediment plumes — clouds of fine particulate matter resuspended by collector vehicles traversing the seafloor and by the discharge of processed sediment from surface vessels. Modelling studies and the limited experimental evidence available suggest that these plumes could disperse over hundreds of kilometres, smothering filter-feeding organisms, disrupting chemosensory navigation in mobile species, and reducing the penetration of the limited bioluminescent light upon which deep-sea food webs partially depend. The recovery timescale for disturbed abyssal ecosystems is measured not in years or decades but in centuries or millennia — a temporal dimension that fundamentally challenges the conventional environmental impact assessment frameworks developed for terrestrial and coastal projects, which typically assume ecosystem recovery within timeframes of five to thirty years.",
      "",
      "F. Proponents of deep-sea mining counter these environmental concerns with several arguments that merit careful examination. They contend that the environmental footprint of seabed extraction, when measured per unit of metal recovered, is substantially smaller than that of equivalent terrestrial operations — a claim supported by lifecycle analyses demonstrating that land-based nickel mining in laterite formations, for instance, generates approximately six times more carbon dioxide per tonne of refined metal than projected nodule processing. They further argue that the concentration of critical minerals in deep-sea deposits would reduce the total area of habitat disturbance required to meet global demand, and that the alternative — continued expansion of terrestrial mining into tropical forests and biodiverse regions — carries environmental costs that critics of deep-sea mining systematically underestimate. The Pacific Island nation of Nauru, sponsor of the company The Metals Company, has been particularly vocal in asserting that resource-poor developing states should not be denied economic opportunities on the basis of precautionary arguments advanced primarily by wealthy nations whose own industrialisation involved extensive environmental destruction.",
      "",
      "G. The scientific community remains deeply divided on the question of whether deep-sea mining can be conducted in a manner consistent with responsible environmental stewardship. In 2023, a joint statement signed by over 800 marine scientists from more than forty countries called for a moratorium on deep-sea mining until sufficient research has been conducted to understand and predict its ecological consequences — a position echoed by the International Union for Conservation of Nature and adopted as official policy by France, Germany, Spain, and several other nations. Opponents of a moratorium counter that delaying extraction indefinitely is itself a policy choice with environmental consequences, inasmuch as it perpetuates reliance on terrestrial mining operations whose ecological impacts are well-documented and severe. The resolution of this debate will hinge ultimately not on whether deep-sea mining entails environmental risk — it manifestly does — but on whether the risks it presents are lesser than, greater than, or merely different from those of the alternatives it would displace.",
    ].join("\n"),
    questions: [
      { kind: "matching-information", question: "a description of the formation process and geological timescale of an oceanic mineral deposit", options: P2_PARAGRAPHS, answer: "B", explanation: "Paragraph B describes polymetallic nodules forming through 'excruciatingly slow precipitation' at rates of 'five to twenty millimetres per million years,' detailing their formation process and geological timescale." },
      { kind: "matching-information", question: "an argument that wealthy nations are being hypocritical in opposing seabed extraction", options: P2_PARAGRAPHS, answer: "F", explanation: "Paragraph F cites Nauru's position that 'resource-poor developing states should not be denied economic opportunities on the basis of precautionary arguments advanced primarily by wealthy nations whose own industrialisation involved extensive environmental destruction.'" },
      { kind: "matching-information", question: "evidence that a seemingly barren environment supports a diverse biological community", options: P2_PARAGRAPHS, answer: "D", explanation: "Paragraph D reveals that despite 'seemingly inhospitable conditions,' the Clarion-Clipperton Zone contains 'over 5,000 species, of which an estimated 70% to 90% are new to science.'" },
      { kind: "matching-information", question: "a legal principle governing the ownership of resources located beyond national borders", options: P2_PARAGRAPHS, answer: "C", explanation: "Paragraph C describes the 'common heritage of mankind' principle from the UN Convention, intended to ensure equitable benefit-sharing of international seabed resources." },
      { kind: "matching-information", question: "the paradox that technologies intended to benefit the environment require environmentally damaging inputs", options: P2_PARAGRAPHS, answer: "A", explanation: "Paragraph A explicitly names this 'irony' — renewable technologies 'designed to reduce humanity's dependence on fossil fuels require vast quantities of metallic minerals' whose extraction causes environmental degradation." },
      { kind: "matching-information", question: "why standard methods for predicting environmental recovery are inadequate in this context", options: P2_PARAGRAPHS, answer: "E", explanation: "Paragraph E states that abyssal recovery timescales of 'centuries or millennia' 'fundamentally challenges the conventional environmental impact assessment frameworks' which 'typically assume ecosystem recovery within timeframes of five to thirty years.'" },
      { kind: "matching-information", question: "a formal collective appeal from researchers for a halt to commercial operations", options: P2_PARAGRAPHS, answer: "G", explanation: "Paragraph G describes 'a joint statement signed by over 800 marine scientists from more than forty countries' calling 'for a moratorium on deep-sea mining.'" },
      { kind: "fill-blank", question: "Polymetallic nodules are found at depths between 4,000 and ______ metres.", options: [], answer: "6,000|6000|6.000", explanation: "The passage states nodules are found 'at depths between 4,000 and 6,000 metres.'" },
      { kind: "fill-blank", question: "The International Seabed Authority is headquartered in ______, Jamaica.", options: [], answer: "Kingston|kingston", explanation: "'headquartered in Kingston, Jamaica.'" },
      { kind: "fill-blank", question: "Studies in the Clarion-Clipperton Zone have identified over ______ species.", options: [], answer: "5,000|5000|5.000", explanation: "'research expeditions have revealed surprising levels of biodiversity... over 5,000 species.'" },
      { kind: "fill-blank", question: "Land-based nickel mining generates approximately ______ times more CO2 per tonne than projected nodule processing.", options: [], answer: "six|6|Six", explanation: "'land-based nickel mining in laterite formations generates approximately six times more carbon dioxide per tonne of refined metal than projected nodule processing.'" },
      { kind: "fill-blank", question: "In 2023, over ______ marine scientists signed a statement calling for a moratorium on deep-sea mining.", options: [], answer: "800|eight hundred", explanation: "'a joint statement signed by over 800 marine scientists.'" },
      { kind: "fill-blank", question: "The regulatory instrument under negotiation that would govern commercial extraction is called the ______.", options: [], answer: "Mining Code|mining code|mining Code", explanation: "'negotiations over the Mining Code — the regulatory instrument that would establish environmental standards, royalty structures, and benefit-sharing mechanisms.'" },
    ],
  },

  // ═══════════════════════════════════════════════════════════
  // PASSAGE 3: The Evolution of Writing Systems (C1, ~960 words, 14 questions)
  // ═══════════════════════════════════════════════════════════
  {
    slug: "mock-ac11-evolution-writing-systems",
    title: "The Evolution of Writing Systems",
    titleVi: "Su tien hoa cua cac he thong chu viet",
    level: "C1",
    category: "mock-academic",
    passage: [
      "The Evolution of Writing Systems",
      "",
      "A. The invention of writing is conventionally regarded as the single most consequential cognitive technology in human history — the innovation that transformed ephemeral speech into durable record, enabling the accumulation, transmission, and critical examination of knowledge across generations in a manner that purely oral traditions, however sophisticated, could not reliably sustain. Yet the circumstances under which writing first emerged remain a subject of considerable scholarly debate, complicated by the fragmentary nature of the archaeological record and by fundamental disagreements over what constitutes a \"writing system\" as opposed to a proto-literate notation or symbolic marking practice. What can be stated with reasonable confidence is that fully developed writing — systems capable of representing the complete range of a spoken language — arose independently in at least three, and possibly as many as five, distinct locations: Mesopotamia, Egypt, China, Mesoamerica, and, more controversially, the Indus Valley and the Rapa Nui script of Easter Island.",
      "",
      "B. The earliest writing system for which the developmental trajectory is best documented is Sumerian cuneiform, which emerged in southern Mesopotamia — modern-day Iraq — during the late fourth millennium BCE. Its origins were not literary or religious but administrative: the earliest clay tablets, recovered from the ancient city of Uruk and dating to approximately 3400-3200 BCE, record inventories of commodities — barley, sheep, textiles, and beer — using numerical signs and stylised pictograms that represented specific goods. The impetus for this innovation appears to have been the unprecedented scale and complexity of the Uruk economy, which, as the first truly urban civilisation with a population that may have exceeded 40,000, generated administrative requirements — tracking agricultural surpluses, allocating labour, recording transactions, and managing temple estates — that exceeded the capacity of human memory and the informal mechanisms of oral communication. Writing, in this account, was invented not to record poetry or preserve mythology but to count grain.",
      "",
      "C. The transition from pictographic to phonetic representation constitutes the most critical conceptual leap in the evolution of writing. Early pictographic systems faced a fundamental limitation: they could effectively represent concrete, visible objects (a fish, a head of grain, a cow) but struggled to encode abstract concepts, grammatical relationships, and proper names — elements essential to the expression of complete linguistic utterances. The solution, arrived at independently by multiple civilisations, was the rebus principle, whereby a sign originally representing a concrete object was repurposed to represent a sound or syllable that happened to be phonetically similar, irrespective of meaning. In Sumerian, for example, the pictogram for \"arrow\" (pronounced \"ti\") came to serve additionally as the sign for \"life\" (also pronounced \"ti\"), a semantic extension made possible by phonetic coincidence rather than conceptual similarity. This shift from logographic to phonetic representation — in which signs denote sounds rather than meanings — effectively liberated writing from the constraint of one-to-one correspondence between symbol and referent, enabling it to represent any utterance that could be spoken.",
      "",
      "D. Egyptian hieroglyphics, whose earliest attestations date to approximately 3250 BCE — making them roughly contemporaneous with, or possibly slightly older than, the Uruk tablets — followed a parallel but distinct developmental path. The hieroglyphic script employed a mixed system combining logograms, phonetic signs representing one, two, or three consonants, and determinatives — semantic classifiers appended to words to indicate their conceptual category (for instance, a seated figure to indicate that the preceding signs denote a person's name). Crucially, the Egyptian system never recorded vowels, a convention inherited by the descendant scripts of the Semitic language family and one that would eventually yield, through a remarkable chain of adaptations, the ancestor of virtually every alphabetic writing system in use today. The Phoenician consonantal script, derived from Egyptian-influenced Proto-Sinaitic inscriptions of the second millennium BCE, was adopted and modified by the Greeks, who added dedicated vowel signs to produce the first true alphabet — a system in which each phoneme, whether consonant or vowel, is represented by a discrete grapheme.",
      "",
      "E. Chinese writing presents a strikingly different evolutionary trajectory, one in which the logographic principle has been retained and elaborated rather than superseded by phonetic transcription. The earliest known Chinese inscriptions — the oracle bone inscriptions of the late Shang dynasty, dating to approximately 1200 BCE — record divination questions carved onto tortoise plastrons and ox scapulae before being subjected to heat-induced cracking, with the resulting patterns interpreted as communications from ancestral spirits. The Shang script already comprised several thousand characters, suggesting a developmental history extending considerably further into the past than the surviving evidence permits us to trace. Modern standard Chinese employs approximately 7,000 characters in routine use, drawn from a total inventory exceeding 50,000, each character representing a morpheme — the minimal unit of meaning — rather than a phoneme.",
      "",
      "F. The evolution of writing materials and instruments has exerted a profound and often underappreciated influence on the graphic form of scripts. Sumerian cuneiform acquired its characteristic wedge-shaped strokes because scribes pressed the corner of a reed stylus into wet clay at standardised angles, a technique that maximised speed and legibility within the constraints of the medium. Egyptian hieroglyphics maintained their elaborate pictorial forms partly because they were carved into stone monuments intended for permanence and public display, while the everyday administrative script — hieratic, and later demotic — underwent progressive simplification under the pressures of rapid cursive writing on papyrus. Similarly, the angular forms of the Arabic and Hebrew scripts reflect their origins in incision on hard surfaces, while the flowing curves of Devanagari developed in response to the practice of writing with ink on palm leaves, where straight horizontal strokes would have split the fibres.",
      "",
      "G. The invention of the alphabet — defined as a system in which each significant speech sound is represented by a separate written sign — is widely considered the most efficient and democratising development in the history of writing. By reducing the number of signs that a literate individual must memorise from several thousand (in logographic systems) or several hundred (in syllabaries) to between twenty and forty, alphabetic scripts dramatically lower the cognitive barrier to literacy, enabling writing and reading to become mass rather than elite skills. This efficiency, however, comes at a cost: alphabetic writing severs the direct visual connection between sign and meaning that logographic systems preserve, rendering the written word an arbitrary sequence of phonetic symbols whose interpretation requires prior knowledge of the spoken language it encodes. The tension between efficiency and transparency — between the compactness of the alphabet and the semantic immediacy of the character — continues to shape debates about script reform, educational policy, and digital text processing in multilingual societies worldwide.",
    ].join("\n"),
    questions: [
      { kind: "matching-sentence-endings", question: "The passage indicates that Sumerian writing was invented because...", options: P3_ENDINGS, answer: "E", explanation: "Paragraph B describes the Uruk civilisation's unprecedented administrative demands — tracking surpluses, allocating labour, managing estates — that 'exceeded the capacity of human memory.' Ending E ('political unification created administrative demands that purely oral communication could not fulfil') captures this, as the scale of urban Uruk required systems beyond oral capacity." },
      { kind: "matching-sentence-endings", question: "The rebus principle was significant because...", options: P3_ENDINGS, answer: "D", explanation: "Paragraph C explains the rebus principle resolved the fundamental limitation of pictographic systems — their inability to represent abstract concepts and grammatical relationships. Ending D ('the invention resolved a limitation that had constrained all previous representational strategies') matches." },
      { kind: "matching-sentence-endings", question: "The development of fully phonetic writing systems...", options: P3_ENDINGS, answer: "F", explanation: "Paragraph C states this shift was 'arrived at independently by multiple civilisations,' and Paragraph D traces a parallel path in Egypt. Ending F ('the transition from ideographic to phonetic representation occurred independently in multiple civilisations') matches." },
      { kind: "matching-sentence-endings", question: "As Sumerian pictograms evolved into cuneiform signs, the result was that...", options: P3_ENDINGS, answer: "C", explanation: "Paragraph C describes how signs originally depicting concrete objects were repurposed to represent sounds, and Paragraph F explains cuneiform's wedge shapes replaced pictorial forms. Ending C ('the original pictographic connection between sign and referent was progressively obscured') captures this process of abstraction." },
      { kind: "matching-sentence-endings", question: "The adoption of the Phoenician script by the Greeks demonstrated that...", options: P3_ENDINGS, answer: "B", explanation: "Paragraph D describes how the Phoenician consonantal script was 'adopted and modified by the Greeks, who added dedicated vowel signs' — taking a Semitic script and adapting it for a fundamentally different language. Ending B ('a single writing system could be adapted to represent languages with fundamentally different structures') matches." },
      { kind: "matching-sentence-endings", question: "The passage suggests that the physical characteristics of cuneiform developed because...", options: P3_ENDINGS, answer: "A", explanation: "Paragraph F explains cuneiform's wedge-shaped strokes resulted from scribes pressing reed styluses 'into wet clay at standardised angles.' Ending A ('the direction of individual strokes became standardised across the scribal community') matches." },
      { kind: "matching-sentence-endings", question: "The passage implies that the adoption of alphabetic writing systems was driven partly by the fact that...", options: P3_ENDINGS, answer: "G", explanation: "Paragraph G describes the alphabet's efficiency in reducing memorisation from thousands of signs to 'between twenty and forty,' lowering barriers to literacy. Ending G ('economic imperatives drove the simplification of complex symbolic inventories') connects to how the reduction in sign numbers made writing more accessible and practical." },
      { kind: "mcq", question: "The author's primary purpose in Paragraph B is to...", options: ["argue that Sumerian literature was more advanced than previously believed", "demonstrate that writing originated as a practical tool rather than an artistic medium", "compare the administrative systems of Uruk with those of other ancient civilisations", "challenge the prevailing archaeological dating of the earliest known inscriptions"], answer: "B", explanation: "Paragraph B emphasises that the earliest tablets 'record inventories of commodities' and that 'Writing was invented not to record poetry or preserve mythology but to count grain' — its origins were practical and administrative, not literary or artistic." },
      { kind: "mcq", question: "According to the passage, what distinguishes the Chinese writing system from most other major scripts?", options: ["It was the earliest writing system to incorporate phonetic elements", "It has maintained the logographic principle rather than transitioning to phonetic representation", "It was developed primarily for religious rather than administrative purposes", "It has undergone fewer reforms and modifications than any other writing system"], answer: "B", explanation: "Paragraph E states Chinese writing presents 'a strikingly different evolutionary trajectory, one in which the logographic principle has been retained and elaborated rather than superseded by phonetic transcription.'" },
      { kind: "mcq", question: "The passage suggests that the absence of vowel signs in Egyptian hieroglyphics was significant because...", options: ["it rendered the script impossible for non-Egyptian speakers to decode", "it established a convention that eventually led to the development of all modern alphabets", "it demonstrated the superiority of consonantal writing over fully phonetic systems", "it prevented the script from being used for literary or religious texts"], answer: "B", explanation: "Paragraph D states the vowelless convention 'would eventually yield, through a remarkable chain of adaptations, the ancestor of virtually every alphabetic writing system in use today' — from Egyptian to Proto-Sinaitic to Phoenician to Greek." },
      { kind: "mcq", question: "The author mentions the flowing curves of Devanagari in Paragraph F to illustrate...", options: ["how religious practices influenced the development of writing systems in South Asia", "that some scripts are inherently more beautiful than others due to their medium", "how the physical writing surface and instrument shaped a script's visual appearance", "that scripts written on organic materials are less durable than those carved in stone"], answer: "C", explanation: "Paragraph F's central argument is that 'writing materials and instruments has exerted a profound influence on the graphic form of scripts.' Devanagari's curves developed 'in response to the practice of writing with ink on palm leaves' — the medium shaped the form." },
      { kind: "mcq", question: "According to Paragraph G, the main disadvantage of alphabetic writing compared to logographic systems is that...", options: ["alphabetic writing requires substantially more space to convey the same information", "alphabetic scripts cannot represent the tonal distinctions present in many languages", "the connection between the written symbol and its meaning is lost in alphabetic systems", "alphabetic systems require more years of formal education to master fully"], answer: "C", explanation: "Paragraph G states 'alphabetic writing severs the direct visual connection between sign and meaning that logographic systems preserve, rendering the written word an arbitrary sequence of phonetic symbols.' The cost is lost semantic transparency." },
      { kind: "mcq", question: "The author's overall approach throughout the passage can best be described as...", options: ["presenting a chronological history of every known writing system from antiquity to the modern era", "analysing the interplay between technological, cognitive, and material factors that shaped the development of writing", "arguing that alphabetic scripts are objectively superior to all other forms of written communication", "cataloguing archaeological discoveries that have overturned previous theories about the origins of literacy"], answer: "B", explanation: "The passage examines how administrative needs (technology), the rebus principle (cognition), and physical media like clay, papyrus, and palm leaves (material factors) all interacted to shape writing's evolution — a multi-factor analytical approach." },
      { kind: "mcq", question: "Which of the following best describes the author's stance on the question of where writing was first invented?", options: ["Confident that Mesopotamia was definitively the earliest location", "Cautious, acknowledging scholarly uncertainty and the limitations of available evidence", "Dismissive of claims that writing arose independently in multiple locations", "Convinced that new discoveries will soon establish a single point of origin"], answer: "B", explanation: "Paragraph A states the question 'remains a subject of considerable scholarly debate, complicated by the fragmentary nature of the archaeological record' and uses hedging language ('with reasonable confidence,' 'possibly as many as five'). The author is cautious and acknowledges uncertainty." },
    ],
  },
];

async function main() {
  const passageIds: string[] = [];

  for (const p of passages) {
    const wc = p.passage.split(/\s+/).filter(Boolean).length;
    const passage = await prisma.readingPassage.upsert({
      where: { slug: p.slug },
      update: { title: p.title, titleVi: p.titleVi, level: p.level, category: p.category, passage: p.passage, wordCount: wc, order: 970 + passages.indexOf(p) },
      create: { slug: p.slug, title: p.title, titleVi: p.titleVi, level: p.level, category: p.category, passage: p.passage, wordCount: wc, order: 970 + passages.indexOf(p) },
    });
    await prisma.readingQuestion.deleteMany({ where: { passageId: passage.id } });
    for (let q = 0; q < p.questions.length; q++) {
      const qn = p.questions[q];
      await prisma.readingQuestion.create({
        data: {
          passageId: passage.id,
          kind: qn.kind,
          question: qn.question,
          options: qn.options,
          answer: qn.answer,
          explanation: qn.explanation,
          order: q,
        },
      });
    }
    passageIds.push(passage.id);
    console.log("  OK [" + p.level + "] " + p.slug + " (" + wc + " words, " + p.questions.length + " questions)");
  }

  const exam = await prisma.readingExam.upsert({
    where: { slug: examSlug },
    update: { title: "IELTS Academic Reading — Test 11", titleVi: "IELTS Academic Reading — De 11", type: "academic", difficulty: "hard", timeMinutes: 60 },
    create: { slug: examSlug, title: "IELTS Academic Reading — Test 11", titleVi: "IELTS Academic Reading — De 11", type: "academic", difficulty: "hard", timeMinutes: 60, order: 10 },
  });
  console.log("\n  OK Exam: " + exam.slug + " (difficulty: hard)");
  await prisma.readingExamSection.deleteMany({ where: { examId: exam.id } });
  for (let i = 0; i < passageIds.length; i++) {
    await prisma.readingExamSection.create({ data: { examId: exam.id, passageId: passageIds[i], order: i } });
  }
  console.log("Done! 3 passages (" + passages.reduce((s, p) => s + p.questions.length, 0) + " questions) + exam + sections.");
}

main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
